apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: redis
spec:
  redis:
    example:
      # HostAddress refers to the address of the Redis host/server
      hostAddress: redis.argo-events.svc:6379
      # Password required for authentication.
      # +optional

#      password:
#        name: name_of_secret_that_holds_password
#        key: key_within_secret_which_holds_password_value

      # DB to use. If not specified, default DB 0 will be used.
      # +optional
      db: 0
      # Channels to subscribe to listen events.
      channels:
        - FOO

#    example-with-url:
#      # URL is the Redis connection URL (parsed using redis.ParseURL).
#      # If set, this takes precedence over hostAddress, password, db, and username.
#      # Format: redis://<user>:<password>@<host>:<port>/<db_number>
#      # +optional
#      url: redis://:mypassword@redis.argo-events.svc:6379/0
#      channels:
#        - FOO
#
#    example-with-url-secret:
#      # URLSecret refers to the K8s secret that holds the Redis connection URL.
#      # If set, this takes precedence over url, hostAddress, and other connection fields.
#      # +optional
#      urlSecret:
#        name: redis-url-secret
#        key: url
#      channels:
#        - FOO

#    example-tls:
#      hostAddress: redis.argo-events.svc:6379
#      db: 0
#      channels:
#        - FOO
#      tls:
#        caCertSecret:
#          name: my-secret
#          key: ca-cert-key
#        clientCertSecret:
#          name: my-secret
#          key: client-cert-key
#        clientKeySecret:
#          name: my-secret
#          key: client-key-key
